# Generated by Django 4.2.2 on 2023-07-08 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_remove_studentinfo_fathers_img_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentinfo',
            unique_together=set(),
        ),
    ]
